// Generated by CoffeeScript 1.8.0

Template.registerHelper('decodeSalleName', function () {
    var SalleInfo = Meteor.roomservice.decodeRoomName(this.name);
    this.place = SalleInfo.place;
    this.fullType = SalleInfo.fullType;
    switch (SalleInfo.aile) {
        case "V":
            this.badgeColor = "badge-primary";
            break;
        case "J":
            this.badgeColor = "badge-warning";
            break;
        case "B":
            this.badgeColor = "badge-success";
            break;
        case "R":
            this.badgeColor = "badge-danger";
            break;
        default :
            this.badgeColor = "";
            break;
    }
    this.shortName = SalleInfo.shortName;
    this.infoName = SalleInfo.infoName;
    if (this.horaire.getTime() != this.debut.getTime()) {
        this.demiheure = true;
    }
    return;
});

